# Setup
title: Selim Heers
tagline: Personal Site
url: https://selimheers.github.io/
paginate: 1
baseurl: ""
permalink: pretty

# Links next to Pagetitle
pages_list:
  # Research: '/research'
  # Teaching: '/teaching'

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Selim Heers
  url: https://selimheers.github.io
  email: heersselim@gmail.com

# Custom vars
version: 3.0.0

theme: jekyll-theme-minimal